bolt-install-deps: comments, fixes, colors

diff --git a/package/bin/bolt-install-deps b/package/bin/bolt-install-deps
--- a/package/bin/bolt-install-deps
+++ b/package/bin/bolt-install-deps
@@ -4,11 +4,15 @@
 # FUNCTIONS
 ###############################################################################
 
+#
+# Print usage information for the bolt-install-deps command to stdout.
+#
 usage() {
     cat << "EOF"
 Copyright (C) 2022 Tobias Koch <tobias.koch@gmail.com>
 
-Install the build dependencies for a Bolt Linux package recipe.
+This tool can be used to install the build dependencies of a Bolt Linux package
+recipe.
 
 USAGE:
 
@@ -25,27 +29,48 @@ OPTIONS:
 EOF
 }
 
+#
+# Print the message passed in $1 to stderr and exit 1.
+#
 die() {
-    echo "bolt-install-deps: error: $1" >&2
+    ESC_RED="\033[0;31m"
+    ESC_BLD="\033[1m"
+    ESC_END="\033[0m"
+
+    if [ -t 1 ]; then
+        echo "${ESC_BLD}bolt-install-deps${ESC_END}: ${ESC_RED}${ESC_BLD}error${ESC_END}: $1" >&2
+    else
+        echo "bolt-install-deps: error: $1" >&2
+    fi
+
     exit 1
 }
 
+#
+# Determine which command to use to install packages.
+#
 determine_install_command() {
     if [ $(cat /etc/os-release | grep ^ID= | cut -d= -f2) = "bolt" ]; then
         echo "opkg install"
-    elif [ -f /etc/debian_release ]; then
+    elif [ -f /etc/debian_version ]; then
         echo "apt-get install"
     else
         die "the current OS platform is not supported."
     fi
 }
 
+#
+# Check if invoking bolt-pack on the input file works, at all.
+#
 try_list_build_dependencies() {
     if ! bolt-pack --build-for="$BUILD_FOR" --list-deps $1 >/dev/null 2>&1; then
         die "failed to list build dependencies, check input file!"
     fi
 }
 
+#
+# Use bolt-pack to list the build dependencies and turn them into a plain list.
+#
 list_build_dependencies() {
     bolt-pack --build-for="$BUILD_FOR" --list-deps $1 | \
         sed -e 's/,/\n/g' -e 's/([^)]\+)//g' | awk '{print $1}'
